#!/bin/bash

[[ $SERVICE_NAME = "workers" ]] && SCALING="manual_scaling:\n  instances: 1" || SCALING=""
[[ $BUGSNAG_API_KEY = "" ]] && BUGSNAG_API_KEY_FIELD="" || BUGSNAG_API_KEY_FIELD="BUGSNAG_API_KEY: ${BUGSNAG_API_KEY}"
[[ $NEW_RELIC_APP_NAME = "" ]] && NEW_RELIC_APP_NAME_FIELD="" || NEW_RELIC_APP_NAME_FIELD="NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}"
[[ $NEW_RELIC_LICENSE_KEY = "" ]] && NEW_RELIC_LICENSE_KEY_FIELD="" || NEW_RELIC_LICENSE_KEY_FIELD="NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}"

echo -e "service: resolution-service-${SERVICE_NAME}
runtime: custom
env: flex

env_variables:
  RESOLUTION_RUNNING_MODE: ${RESOLUTION_RUNNING_MODE}
  RESOLUTION_POSTGRES_HOST: ${RESOLUTION_POSTGRES_HOST}
  RESOLUTION_POSTGRES_USERNAME: ${RESOLUTION_POSTGRES_USERNAME}
  RESOLUTION_POSTGRES_PASSWORD: ${RESOLUTION_POSTGRES_PASSWORD}
  RESOLUTION_POSTGRES_DATABASE: ${RESOLUTION_POSTGRES_DATABASE}
  ETHEREUM_JSON_RPC_API_URL: ${ETHEREUM_JSON_RPC_API_URL}
  VIEWBLOCK_API_KEY: ${VIEWBLOCK_API_KEY}
  ETHEREUM_CHAIN_ID: ${ETHEREUM_CHAIN_ID}
  ZNS_NETWORK: ${ZNS_NETWORK}
  ${BUGSNAG_API_KEY_FIELD}
  ${NEW_RELIC_APP_NAME_FIELD}
  ${NEW_RELIC_LICENSE_KEY_FIELD}

beta_settings:
  cloud_sql_instances: ${GCP_SQL_INSTANCE}

${SCALING}

" > "${SERVICE_NAME}.yaml"
