name: Deploy staging

on:
  workflow_dispatch:
    inputs:
      deployables:
        description: 'api/workers/dispatch.yaml'
        default: 'api workers'
        required: true
env:
  DEPLOY_TIMEOUT: 1200
  IMAGE_NAME: gcr.io/${{ secrets.GCP_STAGING_PROJECT_ID }}/resolution-service:${{ github.sha }}
  RESOLUTION_POSTGRES_HOST: ${{ secrets.RESOLUTION_STAGING_POSTGRES_HOST }}
  RESOLUTION_POSTGRES_USERNAME: ${{ secrets.RESOLUTION_STAGING_POSTGRES_USERNAME }}
  RESOLUTION_POSTGRES_PASSWORD: ${{ secrets.RESOLUTION_STAGING_POSTGRES_PASSWORD }}
  RESOLUTION_POSTGRES_DATABASE: ${{ secrets.RESOLUTION_STAGING_POSTGRES_DATABASE}}
  ETHEREUM_JSON_RPC_API_URL: ${{ secrets.ETHEREUM_TESTNET_JSON_RPC_API_URL}}
  VIEWBLOCK_API_KEY: ${{ secrets.VIEWBLOCK_API_KEY }}
  GCP_SQL_INSTANCE: ${{ secrets.GCP_STAGING_SQL_INSTANCE }}
  ETHEREUM_NETWORK_ID: 4
  ZNS_NETWORK: 'testnet'
  UNS_REGISTRY_EVENTS_STARTING_BLOCK: 8775208
  CNS_REGISTRY_EVENTS_STARTING_BLOCK: 7484092
  CNS_RESOLVER_ADVANCED_EVENTS_STARTING_BLOCK: 7484112
  POLYGON_JSON_RPC_API_URL: ${{ secrets.POLYGON_TESTNET_JSON_RPC_API_URL}}
  POLYGON_NETWORK_ID: 80001
  POLYGON_UNS_REGISTRY_EVENTS_STARTING_BLOCK: 18956099

jobs:
  build_and_push_container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/staging'

      - name: Retrieve cached container image layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build container image and cache layers
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_STAGING }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_STAGING }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Add Google Cloud Container Registry to Docker
        run: gcloud auth configure-docker -q

      - name: Push container image to Google Cotnainer Registry
        run: docker push $IMAGE_NAME

      - name: Save App Engine configurator to reuse between jobs
        uses: actions/upload-artifact@v2
        with:
          name: create-yaml-sh
          path: create-yaml.sh
          retention-days: 1

  deploy_api:
    if: contains(github.event.inputs.deployables, 'api')
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    env:
      SERVICE_NAME: api
      RESOLUTION_RUNNING_MODE: API,MIGRATIONS

    steps:
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_STAGING }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_STAGING }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download App Engine configurator
        uses: actions/download-artifact@v2
        with:
          name: create-yaml-sh
          path: ./

      - name: Create `api.yaml`
        shell: bash
        run: bash create-yaml.sh

      - name: Increase deployment timeout
        run: gcloud config set app/cloud_build_timeout $DEPLOY_TIMEOUT

      - name: Deploy API
        run: gcloud app deploy api.yaml --image-url=$IMAGE_NAME

  deploy_workers:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    if: contains(github.event.inputs.deployables, 'workers')
    env:
      SERVICE_NAME: workers
      RESOLUTION_RUNNING_MODE: ETH_WORKER,ZIL_WORKER,MATIC_WORKER

    steps:
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider:
            ${{ secrets.WORKLOAD_ID_PROVIDER_STAGING }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_STAGING }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Download App Engine configurator
        uses: actions/download-artifact@v2
        with:
          name: create-yaml-sh
          path: ./

      - name: Create `worker.yaml`
        shell: bash
        run: bash create-yaml.sh

      - name: Increase deployment timeout
        run: gcloud config set app/cloud_build_timeout $DEPLOY_TIMEOUT

      - name: Deploy workers
        run: gcloud app deploy workers.yaml --image-url=$IMAGE_NAME
